export default {
  productName: 'product_name',
  productNumber: 'product_number',
  productCategory: 'product_category',
  licenseeType: 'licensee_type',
  bottleSize: 'bottle_size',
  unitsSold: 'units_sold',
  bottlesPerUnit: 'bottles_per_unit',
  basicPricePerUnit: 'basic_price_per_unit',
  bottlesSold: 'bottles_sold',
  litresSold: 'litres_sold',
  costPerUnit: 'cost_per_unit',
  costOfGoodsSold: 'cost_of_goods_sold',
  basicSales: 'basic_sales',
  discount: 'discount',
  licenseeMarkup: 'licensee_markup',
  netSales: 'net_sales',
  hstSales: 'hst_sales',
  hstCogs: 'hst_cogs',
  refundableContainerDeposit: 'refundable_container_deposit',
  totalCollected: 'total_collected',
  unassigned: 'unassigned',
  tiedHouseDiscount: 'tied_house_discount',
  totalRemittance: 'total_remittance'
}
