export default {
  productName: 'product_name',
  vqaNumber: 'VQA_number',
  productCategory: 'product_category',
  licenseeType: 'licensee_type',
  bottleSize: 'bottle_size',
  bottlesSold: 'bottles_sold',
  basicPricePerUnit: 'basic_price_per_unit',
  litresSold: 'litres_sold',
  supplierQuote: 'supplier_quote',
  costPerUnit: 'cost_per_unit',
  costOfGoodsSold: 'cost_of_goods_sold',
  basicSales: 'basic_sales',
  discount: 'discount',
  licenseeMarkup: 'licensee_markup',
  netSales: 'net_sales',
  hstSales: 'hst_sales',
  hstCogs: 'hst_cogs',
  refundableContainerDeposit: 'refundable_container_deposit',
  totalCollected: 'total_collected',
  bottleLevy: 'bottle_levy',
  environmentalFee: 'environmental_fee',
  adminFee: 'admin_fee',
  totalRemittance: 'total_remittance'
}
