export default {
  vqaNumber: 'VQA_number',
  productName: 'product_name',
  productCategory: 'product_category',
  bottleSize: 'bottle_size',
  retailPricePerUnit: 'retail_price_per_unit',
  wrsLitres: 'WRS_litres',
  wrsValue: 'WRS_value',
  directDeliveryLitres: 'direct_delivery_litres',
  directDeliveryValue: 'direct_delivery_value',
  lcboLitres: 'LCBO_litres',
  lcboValue: 'LCBO_value',
  otherProvincesLitres: 'other_provinces_litres',
  otherProvincesValue: 'other_provinces_value',
  exportLitres: 'export_litres',
  exportValue: 'export_value',
  farmersMarketLitres: 'farmers_market_litres',
  farmersMarketValue: 'farmers_market_value',
  miscLitres: 'misc_litres',
  mistValue: 'misc_value',
  totalContainers: 'total_containers',
  totalLitres: 'total_litres',
  totalValue: 'total_value'
}
