export const CREATE_SCRIPTS = {
  NON_VQA: `CREATE TABLE IF NOT EXISTS "non_vqa" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" FLOAT, "units_sold" INTEGER, "bottles_per_unit" FLOAT, "basic_price_per_unit" FLOAT, "bottles_sold" INTEGER, "litres_sold" FLOAT, "cost_per_unit" FLOAT, "cost_of_goods_sold" FLOAT, "basic_sales" FLOAT, "discount" FLOAT, "licensee_markup" FLOAT, "net_sales" FLOAT, "hst_sales" FLOAT, "hst_cogs" FLOAT, "refundable_container_deposit" FLOAT, "total_collected" FLOAT, "unassigned" FLOAT, "tied_house_discount" FLOAT, "total_remittance" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  VQAO: `CREATE TABLE IF NOT EXISTS "vqao" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "VQA_number" VARCHAR(255), "product_name" VARCHAR(255), "product_category" VARCHAR(255), "bottle_size" FLOAT, "retail_price_per_unit" FLOAT, "WRS_litres" FLOAT, "WRS_value" FLOAT, "direct_delivery_litres" FLOAT, "direct_delivery_value" FLOAT, "LCBO_litres" FLOAT, "LCBO_value" FLOAT, "other_provinces_litres" FLOAT, "other_provinces_value" FLOAT, "export_litres" FLOAT, "export_value" FLOAT, "farmers_market_litres" FLOAT, "farmers_market_value" FLOAT, "misc_litres" FLOAT, "total_containers" FLOAT, "total_litres" FLOAT, "total_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  J10: `CREATE TABLE IF NOT EXISTS "j10" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "sales_channel" VARCHAR(255), "total_litres" FLOAT, "total_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  WRS: `CREATE TABLE IF NOT EXISTS "wrs" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" FLOAT, "total_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  LOCATION: `CREATE TABLE IF NOT EXISTS "location" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "location_type" VARCHAR(255), "total_litres" FLOAT, "total_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  FARMERS: `CREATE TABLE IF NOT EXISTS "farmers" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" FLOAT, "total_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  DUTY_FREE: `CREATE TABLE IF NOT EXISTS "duty_free" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "operator_number" VARCHAR(255), "bottle_size" FLOAT, "bottles_per_unit" INTEGER, "units_per_case" INTEGER, "cases_sold" INTEGER, "cost_per_unit" FLOAT, "litres_sold" FLOAT, "cost_of_goods_sold" FLOAT, "net_sales" FLOAT, "total_collected" FLOAT, "total_remittance" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  VQA: `CREATE TABLE IF NOT EXISTS "vqa" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "VQA_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" FLOAT, "bottles_sold" INTEGER, "basic_price_per_unit" FLOAT, "litres_sold" FLOAT, "supplier_quote" FLOAT, "cost_per_unit" FLOAT, "cost_of_goods_sold" FLOAT, "basic_sales" FLOAT, "discount" FLOAT, "licensee_markup" FLOAT, "net_sales" FLOAT, "hst_sales" FLOAT, "hst_cogs" FLOAT, "refundable_container_deposit" FLOAT, "total_collected" FLOAT, "bottle_levy" FLOAT, "environmental_fee" FLOAT, "admin_fee" FLOAT, "total_remittance" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  MISSING_REPORTS: `CREATE TABLE IF NOT EXISTS "missing_reports" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`,
  CONTAINER_DEPOSITS: `CREATE TABLE IF NOT EXISTS "container_deposits" ("id"   SERIAL , "month" TIMESTAMP WITH TIME ZONE, "winery" VARCHAR(255), "deposit_category" VARCHAR(255), "total_containers" INTEGER, "deposit_value" FLOAT, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id"));`
}
