export const CREATE_SCRIPTS = {
  NON_VQA: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='non_vqa' and xtype='U') CREATE TABLE "non_vqa" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" DECIMAL, "units_sold" INTEGER, "bottles_per_unit" DECIMAL, "basic_price_per_unit" DECIMAL, "bottles_sold" INTEGER, "litres_sold" DECIMAL, "cost_per_unit" DECIMAL, "cost_of_goods_sold" DECIMAL, "basic_sales" DECIMAL, "discount" DECIMAL, "licensee_markup" DECIMAL, "net_sales" DECIMAL, "hst_sales" DECIMAL, "hst_cogs" DECIMAL, "refundable_container_deposit" DECIMAL, "total_collected" DECIMAL, "unassigned" DECIMAL, "tied_house_discount" DECIMAL, "total_remittance" DECIMAL, "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  VQAO: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='vqao' and xtype='U') CREATE TABLE "vqao" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "VQA_number" VARCHAR(255), "product_name" VARCHAR(255), "product_category" VARCHAR(255), "bottle_size" DECIMAL, "retail_price_per_unit" DECIMAL, "WRS_litres" DECIMAL, "WRS_value" DECIMAL, "direct_delivery_litres" DECIMAL, "direct_delivery_value" DECIMAL, "LCBO_litres" DECIMAL, "LCBO_value" DECIMAL, "other_provinces_litres" DECIMAL, "other_provinces_value" DECIMAL, "export_litres" DECIMAL, "export_value" DECIMAL, "farmers_market_litres" DECIMAL, "farmers_market_value" DECIMAL, "misc_litres" DECIMAL, "total_containers" DECIMAL, "total_litres" DECIMAL, "total_value" DECIMAL,  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  J10: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='j10' and xtype='U') CREATE TABLE "j10" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "sales_channel" VARCHAR(255), "total_litres" DECIMAL, "total_value" DECIMAL, "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  WRS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='wrs' and xtype='U') CREATE TABLE "wrs" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" DECIMAL, "total_value" DECIMAL, "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  LOCATION: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='location' and xtype='U') CREATE TABLE "location" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "location_type" VARCHAR(255), "total_litres" DECIMAL, "total_value" DECIMAL,  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  FARMERS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='farmers' and xtype='U') CREATE TABLE "farmers" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" DECIMAL, "total_value" DECIMAL,  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  DUTY_FREE: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='duty_free' and xtype='U') CREATE TABLE "duty_free" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "operator_number" VARCHAR(255), "bottle_size" DECIMAL, "bottles_per_unit" INTEGER, "units_per_case" INTEGER, "cases_sold" INTEGER, "cost_per_unit" DECIMAL, "litres_sold" DECIMAL, "cost_of_goods_sold" DECIMAL, "net_sales" DECIMAL, "total_collected" DECIMAL, "total_remittance" DECIMAL, "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  VQA: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='vqa' and xtype='U') CREATE TABLE "vqa" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "VQA_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" DECIMAL, "bottles_sold" INTEGER, "basic_price_per_unit" DECIMAL, "litres_sold" DECIMAL, "supplier_quote" DECIMAL, "cost_per_unit" DECIMAL, "cost_of_goods_sold" DECIMAL, "basic_sales" DECIMAL, "discount" DECIMAL, "licensee_markup" DECIMAL, "net_sales" DECIMAL, "hst_sales" DECIMAL, "hst_cogs" DECIMAL, "refundable_container_deposit" DECIMAL, "total_collected" DECIMAL, "bottle_levy" DECIMAL, "environmental_fee" DECIMAL, "admin_fee" DECIMAL, "total_remittance" DECIMAL,  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  MISSING_REPORTS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='missing_reports' and xtype='U') CREATE TABLE "missing_reports" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  CONTAINER_DEPOSITS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='container_deposits' and xtype='U') CREATE TABLE "container_deposits" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "deposit_category" VARCHAR(255), "total_containers" INTEGER, "deposit_value" DECIMAL,  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`
}
