export const CREATE_SCRIPTS = {
  NON_VQA: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='non_vqa' and xtype='U') CREATE TABLE "non_vqa" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" DECIMAL(18, 3), "units_sold" INTEGER, "bottles_per_unit" DECIMAL(18, 3), "basic_price_per_unit" DECIMAL(18, 3), "bottles_sold" INTEGER, "litres_sold" DECIMAL(18, 3), "cost_per_unit" DECIMAL(18, 3), "cost_of_goods_sold" DECIMAL(18, 3), "basic_sales" DECIMAL(18, 3), "discount" DECIMAL(18, 3), "licensee_markup" DECIMAL(18, 3), "net_sales" DECIMAL(18, 3), "hst_sales" DECIMAL(18, 3), "hst_cogs" DECIMAL(18, 3), "refundable_container_deposit" DECIMAL(18, 3), "total_collected" DECIMAL(18, 3), "unassigned" DECIMAL(18, 3), "tied_house_discount" DECIMAL(18, 3), "total_remittance" DECIMAL(18, 3), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  VQAO: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='vqao' and xtype='U') CREATE TABLE "vqao" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "VQA_number" VARCHAR(255), "product_name" VARCHAR(255), "product_category" VARCHAR(255), "bottle_size" DECIMAL(18, 3), "retail_price_per_unit" DECIMAL(18, 3), "WRS_litres" DECIMAL(18, 3), "WRS_value" DECIMAL(18, 3), "direct_delivery_litres" DECIMAL(18, 3), "direct_delivery_value" DECIMAL(18, 3), "LCBO_litres" DECIMAL(18, 3), "LCBO_value" DECIMAL(18, 3), "other_provinces_litres" DECIMAL(18, 3), "other_provinces_value" DECIMAL(18, 3), "export_litres" DECIMAL(18, 3), "export_value" DECIMAL(18, 3), "farmers_market_litres" DECIMAL(18, 3), "farmers_market_value" DECIMAL(18, 3), "misc_litres" DECIMAL(18, 3), "misc_value" DECIMAL(18, 3), "total_containers" INTEGER, "total_litres" DECIMAL(18, 3), "total_value" DECIMAL(18, 3),  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  J10: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='j10' and xtype='U') CREATE TABLE "j10" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "sales_channel" VARCHAR(255), "total_litres" DECIMAL(18, 3), "total_value" DECIMAL(18, 3), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  WRS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='wrs' and xtype='U') CREATE TABLE "wrs" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" DECIMAL(18, 3), "total_value" DECIMAL(18, 3), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  LOCATION: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='location' and xtype='U') CREATE TABLE "location" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "location_type" VARCHAR(255), "total_litres" DECIMAL(18, 3), "total_value" DECIMAL(18, 3),  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  FARMERS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='farmers' and xtype='U') CREATE TABLE "farmers" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_type" VARCHAR(255), "total_litres" DECIMAL(18, 3), "total_value" DECIMAL(18, 3),  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  DUTY_FREE: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='duty_free' and xtype='U') CREATE TABLE "duty_free" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "product_number" INTEGER, "product_category" VARCHAR(255), "operator_number" VARCHAR(255), "bottle_size" DECIMAL(18, 3), "bottles_per_unit" INTEGER, "units_per_case" INTEGER, "cases_sold" INTEGER, "cost_per_unit" DECIMAL(18, 3), "litres_sold" DECIMAL(18, 3), "cost_of_goods_sold" DECIMAL(18, 3), "net_sales" DECIMAL(18, 3), "total_collected" DECIMAL(18, 3), "total_remittance" DECIMAL(18, 3), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  VQA: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='vqa' and xtype='U') CREATE TABLE "vqa" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "product_name" VARCHAR(255), "VQA_number" INTEGER, "product_category" VARCHAR(255), "licensee_type" VARCHAR(255), "bottle_size" DECIMAL(18, 3), "bottles_sold" INTEGER, "basic_price_per_unit" DECIMAL(18, 3), "litres_sold" DECIMAL(18, 3), "supplier_quote" DECIMAL(18, 3), "cost_per_unit" DECIMAL(18, 3), "cost_of_goods_sold" DECIMAL(18, 3), "basic_sales" DECIMAL(18, 3), "discount" DECIMAL(18, 3), "licensee_markup" DECIMAL(18, 3), "net_sales" DECIMAL(18, 3), "hst_sales" DECIMAL(18, 3), "hst_cogs" DECIMAL(18, 3), "refundable_container_deposit" DECIMAL(18, 3), "total_collected" DECIMAL(18, 3), "bottle_levy" DECIMAL(18, 3), "environmental_fee" DECIMAL(18, 3), "admin_fee" DECIMAL(18, 3), "total_remittance" DECIMAL(18, 3),  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  MISSING_REPORTS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='missing_reports' and xtype='U') CREATE TABLE "missing_reports" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`,
  CONTAINER_DEPOSITS: `IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='container_deposits' and xtype='U') CREATE TABLE "container_deposits" ("id"   INT NOT NULL IDENTITY(1,1) , "month" DATE, "winery" VARCHAR(255), "deposit_category" VARCHAR(255), "channel" VARCHAR(255), "total_containers" INTEGER, "deposit_value" DECIMAL(18, 3),  "createdAt" DATETIME NOT NULL DEFAULT (GETDATE()), PRIMARY KEY ("id"));`
}
